# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9kLMgul3VCDXm62R3wy4o3MocjVplS9
"""

!pip install pinecone-client

import pinecone
import numpy as np
from numpy import dot
from numpy.linalg import norm

# Initialize Pinecone
pinecone.init(api_key="YOUR_API_KEY", environment="gcp-starter")  # Use your actual env
index = pinecone.Index("your-index-name")

# Fetch vectors
ids_to_fetch = ["resume_123", "jd_123"]
vectors = index.fetch(ids=ids_to_fetch)["vectors"]

resume_vec = np.array(vectors["resume_123"]["values"])
jd_vec = np.array(vectors["jd_123"]["values"])

# Compute cosine similarity
def cosine_similarity(vec1, vec2):
    return dot(vec1, vec2) / (norm(vec1) * norm(vec2))

score = cosine_similarity(resume_vec, jd_vec)
print(f"📊 Resume–JD Similarity Score: {score:.4f}")

pip uninstall pinecone-client -y

pip install pinecone

import pinecone

# Initialize Pinecone
pinecone.init(
    api_key="YOUR_API_KEY",
    environment="YOUR_ENV"
)

# Connect to index
index = pinecone.Index("your-index-name")

# Query vector similarity
query_vector = [0.1, 0.2, ...]  # your vector here
result = index.query(vector=query_vector, top_k=5, include_metadata=True)

print(result)
